spring:
  application:
    name: chatDemo

  ai:
    openai:
      api-key: ${OPENAI_API_KEY}  # 从环境变量读取密钥
      base-url: https://api.deepseek.com  #  DeepSeek 的 API 地址
      embedding:
        enabled: false  # 禁用 OpenAI 的嵌入模块，DeepSeek 的 API 暂不支持此功能
      chat:
        options:
          temperature: 1.3  # 控制输出随机性
          model: deepseek-chat  # 指定 DeepSeek 的模型

  datasource:
    url: jdbc:mysql://localhost:3306/chat_demo?useSSL=false&serverTimezone=Asia/Shanghai
    username: root
    password: "12345"